name: "Ubuntu nagios docker CI workflow"


on:
  push:
    branches: [ dev ]

# env:
#     # Environment variable
#     IMAGE_NAME: "ubuntu2004/nagios44"


jobs:

#https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu
  ubuntu-1604-nagios-docker-job:
    name: "ubuntu-16.04 nagios docker job"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "build nagios docker image"
      run: sudo make build-nagios-docker-image              
    - name: "deploy nagios docker image"
      run: sudo make deploy-nagios-docker     

  ubuntu-2004-nagios-docker-job:
    name: "ubuntu-20.04 nagios docker prod job"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "build nagios docker image"
      run: sudo make build-nagios-docker-image         
    - name: "deploy nagios docker image"
      run: sudo make deploy-nagios-docker-prod 

#https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu
  ubuntu-1804-nagios-vagrant-job:
    name: "ubuntu-18.04 nagios vagrant job"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "deploy libvirt"
      run: sudo make deploy-libvirt        
    - name: "deploy vagrant"
      run: sudo make deploy-vagrant 
    - name: "deploy vagrant box"
      run: sudo make deploy-vagrant-boxes   
    # - name: "run vagrant box"
    #   run: |
    #     vagrant up --provider=libvirt "vg-nagios-01"
    #     vagrant status #Check the status of the VMs to see that none of them have been created yet
    #     virsh list --all #show all running KVM/libvirt VMs
    #     vagrant destroy -f           
      
#https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu
  ubuntu-2004-nagios-job:
    name: "ubuntu-20.04 nagios job"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "deploy nagios"
      run: sudo make deploy-nagios